# Generated by Django 5.0.6 on 2024-09-10 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CreatePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('is_publish', models.BooleanField(default=False)),
                ('left', models.IntegerField(blank=True, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('bottom', models.IntegerField(blank=True, null=True)),
                ('color_text', models.CharField(default='black', max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('start_frame', models.IntegerField(blank=True, null=True)),
                ('end_frame', models.IntegerField(blank=True, null=True)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Createpicture', to='main.picture')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promokode', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('gif', models.TextField(blank=True, max_length=1000000000, null=True)),
                ('flag_promokode', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_google_profile', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
