# Generated by Django 5.0.6 on 2024-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpicture',
            name='end_frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createpicture',
            name='start_frame',
            field=models.IntegerField(default=0),
        ),
    ]
