# Generated by Django 5.0.6 on 2024-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='promokode',
            field=models.TextField(max_length=13, unique=True),
        ),
    ]
