# Generated by Django 5.0.6 on 2024-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_promokode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='promokode',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
