# Generated by Django 5.0.6 on 2024-08-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_promokode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='flag_promokode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CreatePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('is_publish', models.BooleanField(default=False)),
                ('left', models.IntegerField(blank=True, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('bottom', models.IntegerField(blank=True, null=True)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Createpicture', to='main.picture')),
            ],
        ),
    ]
