# Generated by Django 5.0.6 on 2024-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_createpicture_color_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_google_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gif',
            field=models.TextField(blank=True, max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='promokode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
