# Generated by Django 5.0.6 on 2024-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_is_google_profile_alter_profile_gif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpicture',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
