# Generated by Django 5.0.6 on 2024-09-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_createpicture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpicture',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
