# Generated by Django 5.0.6 on 2024-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_createpicture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
