# Generated by Django 5.0.6 on 2024-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpicture',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
