# Generated by Django 5.0.6 on 2024-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_createpicture_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpicture',
            name='end_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createpicture',
            name='start_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
